"""Pack generated graphics/documents into one indexed, seekable resource file.

The 12-byte header holds magic, entry count, flags and a directory fingerprint.
Each <16sIH entry stores a name, absolute byte offset and 16-bit byte count.
Payloads are uncompressed; a trailing byte keeps the persistent DOS channel
away from EOF, which would automatically close it in the host-filesystem DOS.
"""
from pathlib import Path
from hashlib import sha256
import struct
import sys

MAGIC = b'KKR1'
ENTRY = struct.Struct('<16sIH')


def read_bundle(path):
    data = Path(path).read_bytes()
    if len(data) < 12 or data[:4] != MAGIC:
        raise ValueError('Invalid Kakuro resource bundle')
    count, reserved = struct.unpack_from('<HH', data, 4)
    if reserved:
        raise ValueError('Unsupported resource bundle flags')
    result = {}
    end = 12 + count * ENTRY.size
    if data[8:12] != sha256(data[12:end]).digest()[:4]:
        raise ValueError('Resource directory checksum mismatch')
    for i in range(count):
        name, offset, size = ENTRY.unpack_from(data, 12 + i * ENTRY.size)
        name = name.rstrip(b'\0').decode('ascii')
        if name in result or offset != end or not size or offset + size >= len(data):
            raise ValueError('Invalid resource directory')
        result[name] = data[offset:offset + size]
        end = offset + size
    if data[end:] != b'\0':
        raise ValueError('Invalid resource bundle terminator')
    return result


def build(directory, names):
    directory = Path(directory)
    names = sorted(names)
    if not names or len(names) > 255 or len(set(names)) != len(names):
        raise ValueError('Invalid resource list')
    offset = 12 + len(names) * ENTRY.size
    entries, payloads, header = [], [], [
        '/* Generated by resource_bundle.py; do not edit. */',
        '#ifndef RESOURCE_INDEX_H', '#define RESOURCE_INDEX_H',
        f'#define RESOURCE_COUNT {len(names)}',
        'typedef struct { unsigned long offset; unsigned int size; } ResourceEntry;']
    rows = []
    for i, name in enumerate(names):
        data = (directory / name).read_bytes()
        if len(name) > 16 or not 0 < len(data) <= 65535:
            raise ValueError(f'Invalid resource: {name}')
        entries.append(ENTRY.pack(name.encode(), offset, len(data)))
        payloads.append(data)
        header.append(f'#define RES_{Path(name).stem} {i}')
        rows.append(f'    {{{offset}UL, {len(data)}U}},')
        offset += len(data)
    signature = sha256(b''.join(entries)).digest()[:4]
    header += [f'#define RESOURCE_LAYOUT_{i} 0x{byte:02x}' for i, byte in enumerate(signature)]
    header += ['#ifdef RESOURCE_IMPLEMENTATION', 'static const ResourceEntry resource_index[RESOURCE_COUNT] = {',
               *rows, '};', '#endif', '#endif', '']
    (directory / 'ASSETS.DAT').write_bytes(MAGIC + struct.pack('<HH', len(names), 0)
        + signature + b''.join(entries) + b''.join(payloads) + b'\0')
    (directory / 'resource_index.h').write_text('\n'.join(header))
    assert read_bundle(directory / 'ASSETS.DAT') == dict(zip(names, payloads))
    print(f'Resource bundle: {len(names)} entries, {offset + 1} bytes')


if __name__ == '__main__':
    build(sys.argv[1], sys.argv[2:])
