// Generated by x16snd from project.yaml; do not edit.
#ifndef SFX_BANK_H
#define SFX_BANK_H

#define SFX_BANK_FILE "sfx.bin"
#define SFX_BANK_ADDR 0xA000

#define SFX_CLICK        0x0000  // 52 bytes, 0.13 s, voices [15]
#define SFX_SELECT       0x0034  // 166 bytes, 0.55 s, voices [14, 15]
#define SFX_BACK         0x00DA  // 163 bytes, 0.55 s, voices [14, 15]
#define SFX_PAGE         0x017D  // 189 bytes, 0.37 s, voices [14, 15]
#define SFX_PLACE1       0x023A  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE2       0x029E  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE3       0x0302  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE4       0x0366  // 102 bytes, 0.37 s, voices [15]
#define SFX_PLACE5       0x03CC  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE6       0x0430  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE7       0x0494  // 100 bytes, 0.37 s, voices [15]
#define SFX_PLACE8       0x04F8  // 102 bytes, 0.37 s, voices [15]
#define SFX_PLACE9       0x055E  // 102 bytes, 0.37 s, voices [15]
#define SFX_VERIFY_ON    0x05C4  // 182 bytes, 0.8 s, voices [14, 15]
#define SFX_VERIFY_OFF   0x067A  // 177 bytes, 0.8 s, voices [14, 15]
#define SFX_WRONG        0x072B  // 103 bytes, 0.42 s, voices [15]
#define SFX_DIALOG       0x0792  // 128 bytes, 1.28 s, voices [14, 15]
#define SFX_SOLVED       0x0812  // 1044 bytes, 3.67 s, voices [12, 13, 14, 15]

#define SFX_COUNT 18
#define SFX_BANK_SIZE 3110

#endif
